#!/usr/bin/env python3

#import rospy
import time

from frea_hardware.head_communicator import HeadCommunicator


def main():
    hc = HeadCommunicator('/dev/ttyUSB0')
    H = [0, 20, 40, 60, 80, 100, 120, 140, 160]
    S = [100, 90, 80, 70, 60, 70, 80, 90, 100]
    V = [100, 100, 80, 80, 100, 80, 80, 100, 100]

    i = 0
    while True:
        h = H[i:] + H[:i]
        s = S[i:] + S[:i]
        v = V[i:] + V[:i]
        hc.setPixelColours(h, s, v)
        time.sleep(0.5)

        i = (i+1) % 9

if __name__ == '__main__':
#    try:
    main()
#    except rospy.ROSInterruptException:
#        pass
