#!/usr/bin/env python3

import rospy
import time

from frea_hardware.head_communicator import HeadCommunicator
from frea_hardware.service_handler import ServiceHandler


def main():
    rospy.init_node("frea_head")
    device = '/dev/ttyUSB0'

    rospy.loginfo("Connecting to FREA's head at '" + device + "'...")

    hc = HeadCommunicator(device)

    rospy.loginfo("Connected to FREA's head at '" + device + "'")

    service_handler = ServiceHandler(hc)

    rospy.loginfo("FREA's head is ready to receive commands")

    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
