frea:
    controllers:
        state:
            type: joint_state_controller/JointStateController
            publish_rate: 50
        position:
            left_ear_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: left_ear_joint
                pid: {p: 10, i: 0, d: 1, i_clamp_min: 0, i_clamp_max: 0}

            right_ear_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: right_ear_joint
                pid: {p: 10, i: 0, d: 1, i_clamp_min: 0, i_clamp_max: 0}

            mouth_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: mouth_joint
                pid: {p: 10, i: 0, d: 1, i_clamp_min: 0, i_clamp_max: 0}

            head_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: head_joint
                pid: {p: 10, i: 0, d: 1, i_clamp_min: 0, i_clamp_max: 0}

            lower_neck_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: lower_neck_joint
                pid: {p: 160, i: 0, d: 16, i_clamp_min: 0, i_clamp_max: 0}

            upper_neck_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: upper_neck_joint
                pid: {p: 160, i: 0, d: 16, i_clamp_min: 0, i_clamp_max: 0}

            upper_tail_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: upper_tail_joint
                pid: {p: 160, i: 0, d: 16, i_clamp_min: 0, i_clamp_max: 0}

            lower_tail_joint_controller:
                type: velocity_controllers/JointPositionController
                joint: lower_tail_joint
                pid: {p: 160, i: 0, d: 16, i_clamp_min: 0, i_clamp_max: 0}

        velocity:
            left_wheel_joint_controller:
                type: effort_controllers/JointVelocityController
                joint: left_wheel_joint
                pid: {p: 8, i: 0, d: 0.0001, i_clamp_min: 0, i_clamp_max: 0}

            right_wheel_joint_controller:
                type: effort_controllers/JointVelocityController
                joint: right_wheel_joint
                pid: {p: 8, i: 0, d: 0.0001, i_clamp_min: 0, i_clamp_max: 0}
